# Comments start with a '#' and go to the end of the line

all: hello1 print1

hello1: hello1.c
	gcc -Wall hello1.c -o hello1

print1: print1.c
	gcc -Wall print1.c -o print1

clean:
	rm -f hello1 print1
